name: Update Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/kivymd/KivyMD/archive/master.zip
        pip install -r requirements.txt || pip install kivy kivymd requests pygithub pytest

    - name: Run tests
      run: |
        pytest
