name: Convert EXE to APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wine
        sudo apt-get install -y apktool

    - name: Convert EXE to APK
      run: |
        wine exe-to-apk-converter.exe --input your_exe_file.exe --output your_apk_file.apk
