name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        unzip commandlinetools-linux-6609375_latest.zip -d cmdline-tools
        sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
        sudo mv cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: bin/*.apk
